export const en = {
  languageCode: "en",
  monday: "Monday",
  tuesday: "Tuesday",
  wednesday: "Wednesday",
  thursday: "Thursday",
  friday: "Friday",
  saturday: "Saturday",
  sunday: "Sunday",
  january: "January",
  february: "February",
  march: "March",
  april: "April",
  may: "May",
  june: "June",
  july: "July",
  august: "August",
  september: "September",
  october: "October",
  november: "November",
  december: "December",
  earnedThisMonth: "Earned this month",
  workedThisMonth: "Worked this month",
  hours: "hours",
  minutes: "minutes",
  seconds: "seconds",
  holiday: "Holiday",
  daySettings: "Day Settings",
  monthSettings: "Month Settings",
  hourlyRate: "Hourly Rate",
  overtimeMultiplier: "Overtime Multiplier",
  displayedCurrency: "Displayed Currency",
  pay: "Pay",
  month: "Month",
  year: "Year",
  weekday: "Weekday",
  disabled: "Disabled",
  color: "Color",
  requiredHours: "Required Hours",
  language: "Language",
  updating: "Updating ...",
  updateColor: "Update color",
} as const;
