export const ro = {
  languageCode: "ro",
  monday: "Luni",
  tuesday: "Marţi",
  wednesday: "Miercuri",
  thursday: "Joi",
  friday: "Vineri",
  saturday: "Sâmbătă",
  sunday: "Duminică",
  january: "Ianuarie",
  february: "Februarie",
  march: "Martie",
  april: "Aprilie",
  may: "Mai",
  june: "Iunie",
  july: "Iulie",
  august: "August",
  september: "Septembrie",
  october: "Octombrie",
  november: "Noiembrie",
  december: "Decembrie",
  earnedThisMonth: "Câștigat luna aceasta",
  workedThisMonth: "Lucrat luna aceasta",
  hours: "ore",
  minutes: "minute",
  seconds: "secunde",
  holiday: "Sărbătoare",
  daySettings: "Setări Zi",
  monthSettings: "Setări Lună",
  hourlyRate: "Salariu orar",
  overtimeMultiplier: "Factor ore supliment.",
  displayedCurrency: "Moneda afișată",
  pay: "Salariu",
  month: "Lună",
  year: "An",
  weekday: "Zi a săptămânii",
  disabled: "Dezactivat",
  color: "Culoare",
  requiredHours: "Ore necesare",
  language: "Limbă",
  updating: "Se actualizează ...",
  updateColor: "Actualizează culori",
} as const;
